name: Kubernetes deply example

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
          
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Clean with Gradle Wrapper
      run: ./gradlew clean

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin
      
    - name: Build Docker image
      run: docker build. -t ${{ secrets.DOCKER_USERNAME}}/${{ secrets. DOCKER_REPOSITORY }}:latest
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_REPOSITORY }}:latest
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@ve.2.e
      with:
        service_account_key: ${{ secrets.GKE_CREDENTIALS }}
        project_id: <PROJECT_ID>
    - name: Deploy to GKE
      run: 1
        gcloud container clusters get-credentials <CLUSTER_NAME> --zone <ZONE>
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
